language: node_js
node_js: stable
before_install:
  - npm config set spin false --global
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  email: vorobeez@gmail.com
  api_key:
    secure: om6vcwnjhi9kfc8oWMyNw11FVuIz/OBh6aMlIQm7HBeYC2miTthda55hTE7EaawRdV2wiUfuigO2/4jztwIk63klARFbb3bE1gjbss+EBIkD+ZfTAPWBFRON8U6IrG4dcpI1yNZkb2owLbCN+qpb4bRr4xMpg3gCD/g+UMAH/sOg3NmRn2QODgbmtYaP120t4zRE/OicVQvw8H1IF+aFHn4rbAVGWUAn/qpGaHwThYt/6YVOE0ZXUJItZGjQaCBwNcQAOln13LIUx5XVWnEKR4HfNJucD0nyJQOBd1/0zOxFzZQP99mVcerq/ScLcAP4+hLhEXCaooMMzukaiOnsfBnCDPwe+yVcYvl2PTYcxlZ0nFMacTxCayOf5y7kiSwlZYJ7lvVhAJiJN+iT390lBNH03aBIzjTqEjZLHZl6rPBZvY01wLzti/JaVqyYXOKaf4Z3ZZ8XnqiqPcDPqfje9yRCxzqqBc/5urGrDtgyCGAgXYUxo5B0nKa76YPF9ktJSW69e92jOcDE+gwfEZyjFIuW+4eEzn16acAr1ftjth9oYVNkv3oFWgSvgUCZFP9WLZNSTV48jooZ4ZX8ghZQsaFmTZ7cHpp2IqTXAgKiFSfW90WbJOCh9gPviKEPdBjWayHbbx/NhxvqGmqHVumR5BonayhmeBY36LyneM5LmFU=
  on:
    tags: true
    branch: master
    repo: 8base/graphiql
