language: node_js
node_js: stable
before_install:
  - npm config set spin false --global
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  email: vorobeez@gmail.com
  api_key:
    secure: Y26Sl/Tjo1/idWC1OwjcjFtVwhTd+jJ++y8nO0MwKNDhk/O+Z88xuycD4DPW5we+/hyhi12zdws6ZRKBjPZgnsYAVAJuWwKuOKQIpZr/1K6Dc6sUs+4kE0sIeU3UxcvZMnj6ln8iAvAaOmJfQ2tIbmgwdno4UIlE1LHh1l56k0rBJ8ApM7FnuMl3UfZS57aKuaWlkRGMjlTf8lGS4Z0Kt5aKA/toOJ3p2hOb5OHbAp+m4M6D+R/MZ/yT7FNZ+PlZP2RmheeyY0D80obzsJe3mDkYcRZPkC7y3pHm/TSVemqhubLChx7M6kDFgW+wGehVYiOp0PvJc/c/Z/cKxabow7kOjXdfY9i8rmXoOqQ28YDJEdqI8eO5XPND7hAnpD7osJpCMWrrew5EK8239dEeBeXJNxF4sZGqNHtV/l4TTv8IWXJvqWc19IP23WXrV1GNDn14MoUkDOsJyxGWV/tf2xHs75oENdK+LQA2jg025POCnvIrupC5MSl/275smDdJdVLxsJMbsxv1H0WM513Ca3SDzBOShbmK/R1L9ez1r/PXUbkVKvdKUcEitZfKV/hiBXoDeSLuo4AdV0JoMNFUNlAqbRfIXjAMGIPnSvkuzMGOQEu3eWHR6yBCrxPa2lJ1uVX2770rSndp53z4EA35AxZzvWvup2isfn6CBPTSPRA=
  on:
    tags: true
    branch: master
    repo: 8base/graphiql
